version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: deploy/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/stop
      timeout: 300
      runas: root
